### ISSUE TITLE
Feature: Tomorrow, Next week, Next month buttons

### ISSUE THREAD

**Issue by Gallevy** [arthurdenner/react-semantic-ui-datepickers#104]
# 🌈 Feature
**What is this feature**
I'm using this library in my project and for my particular use case, I would like to add a button to pick tomorrow/next week/next month in the datepicker (similar to the Today button). 

I would probably add a prop for showTomorrow, showNextWeek, showNextMonth which defaults to false and if true they add a button under the today button. Would probably need to add new values to locales as well.

I would be glad to add this feature, if you see it fitting the component and something you are willing to merge.

**Comment by arthurdenner** [comment]
Hi @Gallevy! 👋 

I get your idea, but I think that this would bloat the UI:

![image](https://user-images.githubusercontent.com/13774309/68600874-91c4de00-04a3-11ea-8dc2-ade3c0bc4b4c.png)
![image](https://user-images.githubusercontent.com/13774309/68600932-a4d7ae00-04a3-11ea-9286-ebed48cd0bc6.png)

I'll leave the issue open to see if more people need this use case.
