### ISSUE TITLE
How do you set current value?

### ISSUE THREAD

**Issue by gencer** [arthurdenner/react-semantic-ui-datepickers#121]
# ❔ Question

How do you set current value/selected value? Because it seems `selected` is not available at TypeScript level.

For example, this doesn't work:

```
<SemanticDatepicker onChange={this.onChange} selected={date} />
```

`selected` is not a member of `SemanticDatepicker`.

Also, lets say I have a date object in my state:

```
<SemanticDatepicker onChange={this.onChange} value={date || null} />
```

This creates an infinite loop in my project. Don't know why. Still investigating.

P.S.: Turkish translation is on its way...

**Comment by arthurdenner** [comment]
Hi @gencer!

`selected` was replaced by `value` on v2 to make the API consistent with others components from Semantic UI React.

If you keep getting infinite loop, can you create a [sandbox](https://codesandbox.io) with a reproducible scenario, please?

**Comment by gencer** [comment]
Hi @arthurdenner,

Thanks for the fast response. I will try to replicate same behavior on sandbox and attach here.

P.S.: I've sent a PR for Turkish language support.

**Comment by gencer** [comment]
Ehrm, I'm going to crack this Monitor if I one more time try codesandbox :)

https://codesandbox.io/s/react-typescript-n214r?fontsize=14&hidenavigation=1&theme=dark

I just don't understand why this guy complain about my render(). It just works on my local test but complains on Codesandbox.😡🤬

But i think you will get the idea. Let me know if you really need a complete working sample. I will re-try without throwing my monitor away. 😅

**Comment by gencer** [comment]
I suspected if `value` is different (in miliseconds) then value given by `onChange` but it seems its exact same. Any ideas on your end?

**Comment by arthurdenner** [comment]
I'm investigating and will post here as soon as I have an update. I had problems with CodeSandbox too and had to solve them locally.

**Comment by arthurdenner** [comment]
So, I couldn't get a sandbox working too - sorry about that - but I made this repo with a working version of your sandbox: https://github.com/arthurdenner/react-semantic-ui-datepickers_issue-121

The changes I did were:

- Check if `gte` is defined before calling `toJSDate` on it;
- Reset `gte` state if `d.value` is falsy (e.g. `null`);

If you these changes don't solve your issue, feel free to open a PR on the repo above with your use case reproducing the infinite loop and I'll investigate more.

**Comment by gencer** [comment]
Hi @arthurdenner!

Thanks for the sample repository. I found it. I just sent a PR. Please have a look at it.

**Comment by arthurdenner** [comment]
Hey @gencer, check my comment in the [PR](https://github.com/arthurdenner/react-semantic-ui-datepickers_issue-121/pull/1), please.
Hopefully that solves your problem. 🙏

**Comment by gencer** [comment]
Yup, that solved my problem.

Thank @arthurdenner for looking into this! 🙏👍
