### ISSUE TITLE
animation={false} prop missing

### ISSUE THREAD

**Issue by dcDalin** [arthurdenner/react-semantic-ui-datepickers#142]
# 🐛 bug report

## Description of the problem
When using typescript, one can not set animation to false as the type is not declared.
## How has this issue affected you? What are you trying to accomplish?
The datepicker flickers when focus is on the input field

**Comment by arthurdenner** [comment]
Hi @dcDalin! :wave: 

I'm afraid I didn't understand this issue.
Where is this `animation` prop you are referring to?

**Comment by dcDalin** [comment]
Hello @arthurdenner,

<img width="825" alt="Screenshot 2020-01-02 at 14 42 41" src="https://user-images.githubusercontent.com/30606041/71665515-4f66a180-2d6e-11ea-852d-4d6a9984fb1e.png">

I want to set animation to false.

**Comment by arthurdenner** [comment]
I see, but this prop doesn't exist on this library. You can see all supported props [here](https://github.com/arthurdenner/react-semantic-ui-datepickers#supported-props). I hope this helps.

**Comment by dcDalin** [comment]
Yes @arthurdenner 

Manually adding **False** as part of the allowed prop fixes this flickering issue. 

Have a look at a similar issue/question raised on Stackoverflow [here](https://stackoverflow.com/questions/57618248/why-datepicker-flicker-in-react-when-focus-in-input-field).

**Comment by arthurdenner** [comment]
I see now, you're talking about the wrong library. :sweat_smile:

You should file an issue [in this repo](https://github.com/arfedulov/semantic-ui-calendar-react) instead.
