### ISSUE TITLE
TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by ktconnolly** [arthurdenner/react-semantic-ui-datepickers#182]
# 🐛 bug report

## Description of the problem

When I click on the date I get the following
    
    83 |   )}
    84 | </div>
    85 | 
    > 86 | <span title={`${months[calendar.month]} ${calendar.year}`}>
    | ^  87 |   {months[calendar.month].slice(0, 3)} {calendar.year}
    88 | </span>
    89 | 

## How has this issue affected you? What are you trying to accomplish?

This only happens when I click on the date itself, if I click on the calendar or clear symbol it works fine.

**Comment by arthurdenner** [comment]
Hi @ktconnolly! :wave: 

Could you provide an example repo?

**Comment by ktconnolly** [comment]
I've realised what it was, I wasn't passing in a Date object correctly for the value, thanks anyway.
