### ISSUE TITLE
Datepicker inside placeholder Segment looks funny

### ISSUE THREAD

**Issue by zacheryph** [arthurdenner/react-semantic-ui-datepickers#21]
# 🐛 bug report

## Description of the problem
When placing a `DatePicker` inside of a `<Segment placeholder>` it hoses the selector a little bit.  Additional CSS is getting applied due to the `placeholder` for buttons that causes the `[<<] [<] DATE [>] [>>]` to get split so the arrows are on top of eachother.

## How has this issue affected you? What are you trying to accomplish?
This is probably a non-common usage of placeholder though I am using segment/placeholder in a Modal for the centering/padding. This modal purely allows selecting a date and closes/executed on date change

Not a big deal. I removed placeholder and replaced with textAlign and style to add padding.

**Comment by arthurdenner** [comment]
This is strange indeed, but it happens due to Semantic UI's `.ui.placeholder.segment .button` selector applying `display: block`.

Thanks for reporting, but I'm not sure I can fix because SUI's selectors are kinda hard to override. Feel free to send a PR with a fix.
