### ISSUE TITLE
Input prop 'autoComplete' not working (input suggestions)

### ISSUE THREAD

**Issue by azmatrana** [arthurdenner/react-semantic-ui-datepickers#215]
# 🐛 bug report

##### Whenever the input field is empty the input is giving the browser suggestions which we can turn off but it is not doing any affect in this component. Below is the image showing that the suggestions for the inputs are available which I want to off. On simple Form.Input autoComplete='off' is working fine but with semantic ui date picker component it isn't working. 

<img width="682" alt="2020-03-18_15-45-59" src="https://user-images.githubusercontent.com/8510334/76953851-36af6600-6931-11ea-8c94-1f979d4ff707.png">

#####  Below is the code picture that I am using to build the date input. 

![image](https://user-images.githubusercontent.com/8510334/76954004-6f4f3f80-6931-11ea-91e6-3faea518a3f4.png)

**Comment by arthurdenner** [comment]
Hi @azmatrana! 👋 

Sorry for the wait to reply, I've been busy with other stuff.

Anyway, I've fixed this in the linked PR.

**Comment by azmatrana** [comment]
@arthurdenner Thanks for the fix, appreciate it. When this update will be available in the node package as well ?

**Comment by arthurdenner** [comment]
Hi @azmatrana! It was released on `2.4.0`. I had an issue with TravisCI so it took longer than expected but it's out now. Please let me know if you find any issues.
