### ISSUE TITLE
`selected` prop doesn't allow for selection change

### ISSUE THREAD

**Issue by jalavosus** [arthurdenner/react-semantic-ui-datepickers#22]
# 🐛 bug report

## Description of the problem
When passing `selected` as a prop with the current day as a parameter, selecting other dates is impossible. 
## How has this issue affected you? What are you trying to accomplish?
I want to have the current day set as the default selected date, as well as allow other dates to be selected.

**Comment by arthurdenner** [comment]
If you provide a `selected` prop, the datepicker turns into a [controlled component](https://reactjs.org/docs/forms.html#controlled-components), therefore you must keep the `selected` prop updated, e.g:

```javascript
class App extends React.Component {
  state = {
    date: new Date(),
  };

  handleDateChange = date => {
    this.setState({ date });
  };

  render() {
    const { date } = this.state;

    return (
      <div className="App">
        <SemanticDatepicker onDateChange={this.handleDateChange} selected={date} />
      </div>
    );
  }
}
```


If I misunderstood the problem you're facing, please provide [a sandbox](https://codesandbox.io) so I can check.

**Comment by jalavosus** [comment]
Ah okay, I was definitely using it wrong. 

Thank you! :)
