### ISSUE TITLE
onBlur fires only when first date selected in SemanticDatepicker when type is range

### ISSUE THREAD

**Issue by primalgreg** [arthurdenner/react-semantic-ui-datepickers#238]
# 🐛 bug report

Thanks for your work, I like the project.

## Description of the problem
Hello, when I use the SemanticDatepicker with type as range, I expect the to catch the onBlur callback when the second date is selected in the range. Right now, it only fires when you select the first date (and not the second date in the range). Seems like the onBlur functionality could be working only for a single date picker

## How has this issue affected you? What are you trying to accomplish?
I'm trying to automatically make a query when a range is set. I can do this by detecting the length of the data.value in onChange but that doesn't seem like the proper way.

### Link to a [sandbox](https://codesandbox.io/): [link]() (optional)
https://codesandbox.io/s/romantic-feather-025i4?file=/src/App.js

**Comment by arthurdenner** [comment]
Hi @primalgreg! 👋
I'm glad you like the project!

Good catch, that seems like a bug. I'll investigate it.
Feel free to contribute with a fix if you have interest in it.

**Comment by arthurdenner** [comment]
Update: I did some changes on the library to better control the focus on the input and the firing of the `onBlur` callback. If you could test the changes by building the library locally, that would be very helpful!

**Comment by gregoryrpitts** [comment]
Damn, that was fast! I'll test it for sure, but I was going to volunteer to try to help out :man_shrugging: next time!

**Comment by gregoryrpitts** [comment]
Would the proper process be to pull the branch into my project? Or to test in codesandbox?

**Comment by arthurdenner** [comment]
Hi @gregoryrpitts! Sorry about that, I had time yesterday and decide to take on it. I always say "feel free to work on it", but no one does it. If you have interest in working on another issue, don't hesitate to comment!

About trying the changes, I've managed to publish `2.6.0-beta.0`, please try it. I published from my local machine instead of TravisCI, but I think I did it correctly 🤞

**Comment by arthurdenner** [comment]
Hey, any updates on this? Does the beta version fixes your issue? 😄

**Comment by primalgreg** [comment]
Hi Arthur,

Sorry, I got caught up in some backend refactoring and haven't even opened
up the React Project in a week or so. I'll verify either today or tomorrow.

- Greg

**Comment by primalgreg** [comment]
Arthur,

I tested in my project and it works as expected. Thanks so much for a quick
response! Open source projects are thankless sometimes, and can be the
brunt of disrespect from developers who don't respect the time and effort.

Does the project have a fund I can donate to? I'm just an individual so
it's chump change but I want to recognize effort.

- Greg

**Comment by arthurdenner** [comment]
@primalgreg, thank you for the kind words. I've applied for GitHub Sponsors though, but it'll take some time to my application to be reviewed, so there's no way to donate at the moment.

I'll release a new stable version with the changes.

Best regards.

**Comment by arthurdenner** [comment]
@primalgreg, I have GitHub Sponsors enabled now in case you're still interested in donating 🎉

**Comment by gregoryrpitts** [comment]
Thank Arthur, I signed up. Best wishes.

**Comment by arthurdenner** [comment]
Thank you very much, that means a lot!
