### ISSUE TITLE
How to set date value in redux-form?

### ISSUE THREAD

**Issue by saikumarkunchaa** [arthurdenner/react-semantic-ui-datepickers#258]
How to set date value in redux-form?
dispatch(change('FormData', 'date1', value));

<Field
                    name="date1"
                    component={SemanticDatepicker}
                    placeholder="Date"
                  />

**Comment by saikumarkunchaa** [comment]
@arthurdenner  please help me to do this.

**Comment by arthurdenner** [comment]
Hi @saikumarkunchaa! 👋 

I've created [this sandbox](https://codesandbox.io/s/react-sui-datepickers-redux-form-ndd6b) to describe the usage of this library with `redux-form` using the `Field` and `dispatch` APIs.

Let me know if you have any questions or suggestions.

**Comment by saikumarkunchaa** [comment]
Thank you for quick response @arthurdenner
