### ISSUE TITLE
Can't change width of input

### ISSUE THREAD

**Issue by FSerg** [arthurdenner/react-semantic-ui-datepickers#26]
# ❔ Question

Can't change the width of the input.
The CSS customization is available only for cells :(
I tried to use id property like this:
`<SemanticDatepicker type="range" id="x123" />`
and CSS
`#x132 { width: 500px; }`
But it doesn't work.

Are there any ideas?

**Comment by arthurdenner** [comment]
Hi @FSerg :wave: 

This issue is probably caused by what I related in #19.

Unfortunately, I didn't take any time to check and try to solve it.

Any help would be appreciated. :pray:

**Comment by xzessmedia** [comment]
hmm i can not confirm this,
i was able to change the width for the input,

`.ui.icon.input input {

    padding-right: 2.67142857em !important;
    width: 500px;

}`

for the class clndr-control
and even clndr-cell

without any problems, just normal css knowledge

**Comment by arthurdenner** [comment]
Hi @xzessmedia! :wave: 

Yep, you can control it with CSS, but I think that the perfect behavior would be if just worked™ without any extra work. The problem is more visible if you try to use the component inside a `Form.Group`.

**Comment by brad12s** [comment]
Running into same issues where the last 2 digits are being cutoff.  
We're using inside a <Form.Group>.  
Editing the css renders **all** UI input fields:

 `.ui.form .field .ui.icon.input {
    width: 312px;
}`
