### ISSUE TITLE
How do we pass a custom icon

### ISSUE THREAD

**Issue by abhikur** [arthurdenner/react-semantic-ui-datepickers#296]
# ❔ Question

I want to rendering SemanticDatePicker with a custom icon instead of close icon. How do I do that? 
I tried passing a className in the icon prop but that doesn't work. Please help me for this

**Comment by arthurdenner** [comment]
Hi @abhikur! 👋 

You can customize the icon when there are no selected dates by passing a string to the `icon` prop. The string needs to be one of the values listed [here](https://react.semantic-ui.com/elements/icon/).

The "clear" icon is not customizable at the moment but I can take a look into that. Out of curiosity, what's your use case, which icon would you like to use?

**Comment by arthurdenner** [comment]
@abhikur, I have put up a PR for adding support for custom `icon` and `clearIcon` props - `clearIcon` is a new prop. If the PR gets merged, you'll be able to pass any valid string/icon from SemanticUIReact or a custom component to both props.

You can play with [here](https://react-semantic-ui-datepickers-git-feat-support-custom-icons.arthurdenner.vercel.app/?path=/story/datepickers--with-custom-icons) and get the source code for the example [here](https://github.com/arthurdenner/react-semantic-ui-datepickers/blob/feat/support-custom-icons/stories/index.stories.tsx#L97).

**Comment by arthurdenner** [comment]
Feel free to review the proposed PR and suggest any fixes, changes or improvements.

I've also published the changes under the version `2.8.0-beta.0` so that you can test on a project as well if you prefer.

**Comment by abhikur** [comment]
Hi @arthurdenner, thanks for the quick reply. clearable={false} did the trick. I am able to see the calendar icon instead of close now. But yeah if we can pass custom icons (not from the list) then it would be great. I saw your PR I hope that would do the same what I am asking for.

**Comment by abhikur** [comment]
@arthurdenner I am able to pass the custom icon now. This looks good. Now, it will be great if you can merge this PR so that I can use proper version. Thanks

**Comment by abhikur** [comment]
@arthurdenner One more question I have is - Is there any way I can get the time as well along with the selected date. For ex - I select a date from the datepicker and as a date object I get datetime instead of just date. Right now the time is coming as 00:00:00 in the date but I want the current time. If it is not yet built, should I can create a issue card for this?

**Comment by arthurdenner** [comment]
@abhikur, nice that the proposed change works for you. I'll merge the PR soon and release a stable version.

Regarding the date, that's not supported and I don't plan to add it as it would be a breaking change and could lead to more problems than benefits.
