### ISSUE TITLE
Add ability to change date input via props after  initial state has been set 

### ISSUE THREAD

**Issue by icameron** [arthurdenner/react-semantic-ui-datepickers#3]
Setting selected date after the initial state has been set. i,e, a button on the page with a set date

**Comment by arthurdenner** [comment]
@icameron, thanks for the suggestion. Just to clarify if I understood correctly, do you mean to make the datepicker a [controlled component](https://reactjs.org/docs/forms.html#controlled-components)?

**Comment by icameron** [comment]
Yes that would work

**Comment by icameron** [comment]
perfect!
