### ISSUE TITLE
Way to remove Today button from picker?

### ISSUE THREAD

**Issue by bhkangw** [arthurdenner/react-semantic-ui-datepickers#302]
Looked through docs and couldn't find a way to remove the large 'Today' button at the bottom of the datepicker. Would love to keep it simple and only display the calendar itself.

If there's not a way, is there a way to change the size of the date picker?

**Comment by arthurdenner** [comment]
Hi @bhkangw! 👋 

Yes, it's possible to remove it by passing `showToday={false}` to the component. However, if you're using TypeScript, this would display an error as the prop was not declared in the definitions. I've pushed a fix for it.
