### ISSUE TITLE
Can I get year selection option?

### ISSUE THREAD

**Issue by saikumarkunchaa** [arthurdenner/react-semantic-ui-datepickers#307]
Could you please let me know year selection option here now it is going to 12months back but I need year selection

**Comment by arthurdenner** [comment]
Hi @saikumarkunchaa! 👋

Year selection is not supported at the moment, but feel free to submit a PR if you're interested in adding it.

**Comment by saikumarkunchaa** [comment]
Hi Arthurdenner,
Thank you for your response.

Thanks,
Saikumar K
