### ISSUE TITLE
Time/hours/minutes input zone

### ISSUE THREAD

**Issue by pifpafpof-thomasL** [arthurdenner/react-semantic-ui-datepickers#31]
# 🌈 Optional field to also input a time in hours:minutes:seconds

Thanks for this great lib !

I now need to add this feature on a range Component 
          <SemanticDatepicker
            onDateChange={(dateRange) => this.setState({ dateRange })}
            type="range"
            selected={dateRange}
          />

2 input time cells could be added below the "day of the moment component"

The selected output date would then also include the time selected.
For the HH:MM:SS being the time being set is equal to the current time, but it is too bad  the user is not able to specify something different.

**Comment by arthurdenner** [comment]
Hi @pifpafpof-thomasL! :wave: 

Thanks for the suggestion!

I've marked this as an `enhancement` and feel free to work on it if you like.
