### ISSUE TITLE
pointing prop is not working / not defined in typescript interface

### ISSUE THREAD

**Issue by jaaaco** [arthurdenner/react-semantic-ui-datepickers#32]
When trying to use documented "pointing" prop in react component I got an error saying that it's not defined

**Comment by arthurdenner** [comment]
Hi @jaaaco! :wave: 

You are right, the `pointing` prop is not documented.

Would you be interested in adding it through a PR?

**Comment by arthurdenner** [comment]
Done in #34. Thanks @jaaaco!
