### ISSUE TITLE
className for SemanticDatepicker?

### ISSUE THREAD

**Issue by unbugged** [arthurdenner/react-semantic-ui-datepickers#337]
When validating the input, it would be nice to attach a class into it on error, for instance to surround it with a red border. 

Is it possible to pass a className for SemanticDatepicker?

**Comment by arthurdenner** [comment]
Hi @unbugged! 👋 

For the use case you mentioned, display an error state, I'd suggest the `error` prop, which is passed down to `semantic-ui-react`'s Input - [see here](https://react.semantic-ui.com/elements/input/#states-error).

Regarding the `className` prop, that wasn't supported, thanks for pointing that out! I've added support for it in #346, it's passed down to semantic-ui-react`'s Input as well.

**Comment by arthurdenner** [comment]
The change will be released once #336 is merged.
