### ISSUE TITLE
Unable to see *required star on the label

### ISSUE THREAD

**Issue by dandalgatov** [arthurdenner/react-semantic-ui-datepickers#374]
Here is 2 fields side by side, they both have "required" tag, but the little star  *  doesn't show up on the date picker label. You can see screenshot attached. [](url)

        <Form.Group widths='equal'>
          <Form.Select fluid required
            label='Group'
            placeholder='Group'
            name='group'
            options={groupOptions}
            onChange={handleChange}
          />
          <SemanticDatepicker fluid required
            label='Date'
            name='date'
            value={formData.date}
            onChange={handleChange} />
        </Form.Group>

<img width="1171" alt="Screen Shot 2020-08-24 at 5 43 30 PM" src="https://user-images.githubusercontent.com/63475820/91099529-7d686100-e631-11ea-89c9-dd7630479291.png">

**Comment by arthurdenner** [comment]
Hi @dandalgatov! 👋 

Thank you for reporting this. I've put a PR to fix it and it'll be released soon.
