### ISSUE TITLE
Add support for inverted style

### ISSUE THREAD

**Issue by ddeisadze** [arthurdenner/react-semantic-ui-datepickers#391]
# 🐛 bug report
## Description of the problem
If datepicker is nested within a semantic-ui element e.g. Table with inverted=True, the text inside the datetime dialog will be styled with an inverted theme (color: white) and the dialog box will also stay white, which does not play well. We could manually override the style but it would be nice to pass in a prop `inverted`

### Link to a [sandbox](https://codesandbox.io/): [link]() (optional)
![image](https://user-images.githubusercontent.com/1585369/92398421-86a80200-f0f6-11ea-9f75-85e224c6f727.png)

**Comment by arthurdenner** [comment]
Hi @ddeisadze! 👋 

Thank you for reporting this.

I opened a draft PR to work on this in the following days. I hope to finish soon, but I can't provide an ETA though.

For some components from `semantic-ui-react` I can just pass down the prop, but for the custom elements, I need to see what to do.

Any suggestion and help is welcome 😃

**Comment by arthurdenner** [comment]
@ddeisadze, whenever you have some time, please test the new version with support for the prop `inverted`. If you find any issues or have any suggestions, feel free to create new issues for them.
