### ISSUE TITLE
Yup validation

### ISSUE THREAD

**Issue by euobrunocosta** [arthurdenner/react-semantic-ui-datepickers#430]
Can I validate the field with yup?

`dataAgendamento: yup.date().required()`

**Comment by arthurdenner** [comment]
Hi @euobrunocosta! 👋 

You definitely can. You can find an example of usage with Formik and yup [in this sandbox](https://codesandbox.io/s/react-semantic-ui-datepickers-example-forked-my07l?file=/src/Form.js).
