### ISSUE TITLE
Align Right?

### ISSUE THREAD

**Issue by kcolwell** [arthurdenner/react-semantic-ui-datepickers#562]
# ❔ Question

I see that clndr-left is automatically applied to the main div. Is there a method for switching this to clndr-right?

**Comment by arthurdenner** [comment]
Hi @kcolwell! 👋🏽 

You can pass the prop `pointing="right"` to get the behaviour you've described.

You can test the options at https://react-semantic-ui-datepickers.now.sh/. There is a "Pointing" option in the sidebar.

**Comment by kcolwell** [comment]
Sorry for being dense but is there a way to actually see the code on storybook?

**Comment by arthurdenner** [comment]
Not currently, there's probably some way to tweak it in Storybook. I'll have a look.

And no worries, feel free to ask anything!

**Comment by arthurdenner** [comment]
I had a look and didn't find a way to render the source based on the knobs, but it's possible to display the source of the story itself. I've added that in https://github.com/arthurdenner/react-semantic-ui-datepickers/pull/563. I hope it's helpful somehow!
