### ISSUE TITLE
Setting the maxDate to a day in the current month still shows the next month

### ISSUE THREAD

**Issue by SaintWacko** [arthurdenner/react-semantic-ui-datepickers#609]
The 'range' type datepicker displays two adjacent months side by side, defaulting to the current month and the next month. When setting a maxDate in the current month, it still behaves the same way, resulting in an entirely blacked out month appearing in the datepicker. I would expect it to show the current month and the previous month instead.

As an alternative, adding support for Dayzed's monthsToDisplay prop would allow me to limit the datepicker to just show a single month.

**Comment by arthurdenner** [comment]
Hi @SaintWacko! 👋🏽 

Thank you for reporting this. Sorry for the wait to reply, I was on a short vacation recently.

After investigating the issue you've described, I noticed it can be solved by passing a `date` prop to `dayzed`. This prop is "used to calculate what month to display on initial render", so you could set this to `subMonths(maxDate, 1)`.

However, this library currently overrides this prop with [this piece of code](https://github.com/arthurdenner/react-semantic-ui-datepickers/blob/develop/src/index.tsx#L155-L164).

I think the correct behaviour would be to respect the prop and fallback if not set.

I created #611 for that and released a beta version - `2.13.2-beta.1`.
Can you please test the approach suggested above with this beta version to see if it works for you?

**Comment by SaintWacko** [comment]
No worries, hope you enjoyed your vacation. And that does indeed fix how the months display, thank you!

**Comment by arthurdenner** [comment]
Awesome. Thank you for the quick feedback. It's now published as a stable version - `2.13.2`.
