### ISSUE TITLE
Does not work on RunKit out of the box

### ISSUE THREAD

**Issue by kn-ivan** [arthurdenner/react-semantic-ui-datepickers#780]
# 🐛 bug report

## Description of the problem

If I go to the NPMJS page and then go to RunKit, then I click Run, I get an error, right out of the box, without editing anything.

## How has this issue affected you? What are you trying to accomplish?

I got this bug while evaluating your package for possible use in my project.  It's not good, because it makes me worry that it won't work out of the box, if I install it into my project, and I won't know exactly how to get it to work.

### Link to a [sandbox](https://codesandbox.io/): [link]() (optional)

https://npm.runkit.com/react-semantic-ui-datepickers

<img width="853" alt="image" src="https://user-images.githubusercontent.com/97128000/178610246-1990b160-1107-41c3-b9f8-bcbe8eb325af.png">

**Comment by arthurdenner** [comment]
As the error stacktrace shows, `dayzed` is a dependency of this library and requires `prop-types`. We don't have control over this dependency and this library isn't supposed to bundle `prop-types` either.
