### ISSUE TITLE
Better locale typing

### ISSUE THREAD

**Issue by kn-ivan** [arthurdenner/react-semantic-ui-datepickers#781]
# Better locale typing

Currently, you only have limited locales in LocaleOptions.  

```
export declare type LocaleOptions = 'bg-BG' | 'ca-ES' | 'cs-CZ' | 'de-DE' | 'el-GR' | 'en-US' | 'es-ES' | 'et-EE' | 'fi-FI' | 'fr-FR' | 'he-IL' | 'it-IT' | 'ja-JP' | 'ko-KR' | 'nb-NO' | 'nl-NL' | 'nn-NO' | 'pl-PL' | 'pt-BR' | 'ro-RO' | 'ru-RU' | 'sk-SK' | 'sv-SE' | 'tr-TR' | 'zh-CN';
```

You don't, for example, have 'hi-IN' for Hindi, India.  Why so few?  In order for this package to be of any use to anyone who will use localization, this is effectively useless, except for people who only happen use the locales you provided in TypeScript.

It's a no-go to add new ones, unless I want to just totally fork your repo, in which case I'd miss out on updates.

My suggestion is either (a) put in _all_ locales into the enum (but even that might be bad as the world changes -- there might be new countries or even new languages that are added), or (b) just make it `string`, which would allow for any locales.

I realize `string` would be a pretty wide net, but sometimes simples is better, and I can't think of a better way, without potentially keeping people from being able to use any locale.

1. Change LocalOptions to simply be `string`.
2. Put the locales you currently have in as example in the comments, so people get the general idea.

```
/*
 * locales such as 'bg-BG' | 'ca-ES' | 'cs-CZ' | 'de-DE' | 'el-GR' | 'en-US' | 'es-ES' | 'et-EE' | 'fi-FI' | 
 * 'fr-FR' | 'he-IL' | 'it-IT' | 'ja-JP' | 'ko-KR' | 'nb-NO' | 'nl-NL' | 'nn-NO' | 'pl-PL' | 'pt-BR' | 'ro-RO' | 
 * 'ru-RU' | 'sk-SK' | 'sv-SE' | 'tr-TR' | 'zh-CN'
 */
export declare type LocaleOptions = string;
```

**Comment by arthurdenner** [comment]
Hi there. The locales in the prop are the ones in the repo: https://github.com/arthurdenner/react-semantic-ui-datepickers/tree/develop/src/locales. To have more locales, we'd need more files (see #2).
