### ISSUE TITLE
Today button triggers form onSubmit

### ISSUE THREAD

**Issue by edwin-tandiono** [arthurdenner/react-semantic-ui-datepickers#806]
# 🐛 bug report

## Description of the problem
I have a range datepicker rendered inside a form with `onSubmit` set to a function. When clicking the today button on the datepicker, the form received a submit event and ran the `onSubmit` function.

## How has this issue affected you? What are you trying to accomplish?
When user clicks the today button, I expect the calendar to select today's date without submitting the form. Auto-submitting the form might be problematic if user wants to fill other field before submitting.

### Reproducible sandbox: https://4vtf5l.csb.app/

Steps to reproduce:
1. Open datepicker
2. Click on today button
3. Alert "CHANGE" triggered (expected because onChange runs)
4. Alert "SUBMIT" is also triggered (not expected)

**Comment by arthurdenner** [comment]
Hi @edwin-tandiono! 👋🏽 
Thanks for reporting this and for the sandbox.

I've opened a PR that adds `type="button"` to all of the rendered buttons so that none of them will trigger the form submission in your scenario. The version with the fix will be published soon.
